Frontend:
  impl: SimpleO3
  ipc: 6
  inst_window_depth: 200
  clock_ratio: 1
  num_expected_insts: 100000000    # 100M
#  num_expected_insts: 300000000    # 300M
#  num_expected_insts: 1000000000    # 1G
#  num_expected_insts: 10000000000  # 10G
#  num_expected_insts: 20000000000  # 20G
#  num_expected_insts: 1000000 # testing
  traces:
    TRACES
#  - traces/in-memory-analytics-core-1/trace.cpu0:0
#  - traces/in-memory-analytics-core-1/trace.cpu0:1
#  - traces/in-memory-analytics-core-1/trace.cpu0:2
#  - traces/in-memory-analytics-core-1/trace.cpu0:3
#  - trace-in-memory-analytics-core-1:4

  llc_latency: 50
  llc_linesize: 64
  llc_associativity: 8
  llc_num_mshr_per_core: 16
  llc_capacity_per_core: 2MB

  cows_enable: true
  cows_accel_zero_page: true
  cows_dram_latency_on_translation: 134
  cows_cache_access_latency: 8
  cows_cache2llc_ratio: 8
  cows_cache_assoc: 8
  dram_page_bytes: 8KB
  cows_stats_file: cows_stats
  cows_replacement: LRU_nohit

  Translation:
    impl: NoTranslation
    max_addr: 9223372036854775807


MemorySystem:
  impl: GenericDRAM
  clock_ratio: 1

  DRAM:
    impl: DDR5-cow
    drampower_enable: true
    high_temp: false
#    high_temp: true
    org:
#      preset: DDR5_32Gb_x8
      preset: DDR5_64Gb_x8
      channel: 12
      rank: 2
    timing:
#      preset: DDR5_3200C
      preset: DDR5_8000C
    voltage:
    current:
    RFM:
      BRC: 2

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: ClosedRowPolicy
#      impl: OpenRowPolicy
      cap: 8
#      cap: 16 #almost as good as open policy
#      cap: 4
    plugins:

  AddrMapper:
#    impl: RoBaRaCoCh
    impl: RoBaRaChCo
